apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.subnet-id: 87335469-74cb-439a-aaa2-92b1475ca1bf
    kubernetes.io/elb.enterpriseID: "0"
    kubernetes.io/elb.autocreate: >-
      {"type":"public","bandwidth_name":"cce-bandwidth-1664797272505","bandwidth_chargemode":"traffic","bandwidth_size":5,"bandwidth_sharetype":"PER","eip_type":"5_bgp"}
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
    kubernetes.io/elb.health-check-flag: "off"
  name: {{ include "lab-lae.fullname" . }}
  labels:
    {{- include "lab-lae.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
  selector:
    {{- include "lab-lae.selectorLabels" . | nindent 4 }}
